<a href="https://colab.research.google.com/github/Pedro-Boechat/periodo1trainee/blob/main/periodo2clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.cluster import KMeans

In [ ]:
df = pd.read_csv('/content/wine.csv')

In [ ]:
df.head()

   Alcohol  Malic_Acid   Ash  ...   Hue  OD280  Proline
0    14.23        1.71  2.43  ...  1.04   3.92     1065
1    13.20        1.78  2.14  ...  1.05   3.40     1050
2    13.16        2.36  2.67  ...  1.03   3.17     1185
3    14.37        1.95  2.50  ...  0.86   3.45     1480
4    13.24        2.59  2.87  ...  1.04   2.93      735

[5 rows x 13 columns]

In [ ]:
df.isna().sum()

Alcohol                 0
Malic_Acid              0
Ash                     0
Ash_Alcanity            0
Magnesium               0
Total_Phenols           0
Flavanoids              0
Nonflavanoid_Phenols    0
Proanthocyanins         0
Color_Intensity         0
Hue                     0
OD280                   0
Proline                 0
dtype: int64

In [ ]:
# Normalizando os dados
colunas = df.columns
for i in colunas:
  df[i] = df[i]/df[i].max()

df.head()

    Alcohol  Malic_Acid       Ash  ...       Hue   OD280   Proline
0  0.959541    0.294828  0.752322  ...  0.608187  0.9800  0.633929
1  0.890088    0.306897  0.662539  ...  0.614035  0.8500  0.625000
2  0.887390    0.406897  0.826625  ...  0.602339  0.7925  0.705357
3  0.968982    0.336207  0.773994  ...  0.502924  0.8625  0.880952
4  0.892785    0.446552  0.888545  ...  0.608187  0.7325  0.437500

[5 rows x 13 columns]

In [ ]:
from sklearn.metrics import silhouette_samples, silhouette_score
k = 1
while k < 10:
  k += 1
  kmeans = KMeans(n_clusters=k)
  pred = kmeans.fit_predict(df)
  print(silhouette_score(df, kmeans.labels_))

  # Quanto maior for o score silhouette, mais adequada é a quantidade de clusters.

0.32367418407063553
0.29017591337178367
0.25921518958400463
0.23404346413380886
0.20238784496662532
0.16680672130274596
0.16058377340258384
0.15929808613500787
0.1646564787085589

In [ ]:
kmeans = KMeans(n_clusters=2)
pred = kmeans.fit_predict(df)

In [ ]:
kmeans.cluster_centers_

array([[0.86933068, 0.5143928 , 0.74177772, 0.69922705, 0.60109143,
        0.44135664, 0.19890448, 0.69784805, 0.32790867, 0.47      ,
        0.45958132, 0.4673913 , 0.35452036],
       [0.88127215, 0.33218918, 0.7269009 , 0.61856269, 0.62492921,
        0.68658375, 0.5264213 , 0.45357242, 0.51811798, 0.33786168,
        0.623424  , 0.77036697, 0.50158912]])